version: '3.8'

services:
  play-infor-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: play-infor-website
    networks:
      - play-infor-network

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - play-infor-web
    restart: unless-stopped
    container_name: play-infor-nginx
    networks:
      - play-infor-network
    profiles:
      - production

networks:
  play-infor-network:
    driver: bridge

volumes:
  nginx_logs:
